### ISSUE TITLE
Input a specific state to find the best move?

### ISSUE THREAD

**Issue by alpha-106** [qpwoeirut/2048-solver#2]
I'm trying to win the game on a device other than my PC.
Is there a way to input a specific state of the game into the solver and get a move suggestion?

**Comment by qpwoeirut** [comment]
Sorry for responding so late; I haven't worked on this project in a while.

I wrote an editor page that does pretty much exactly what you're describing in order to test the AIs, but I hadn't published it. You can find it at [/editor](https://qpwoeirut.github.io/2048/editor). It might be a bit buggy; it was completely broken for the last year or so and I just got it working again.
